[package]
name = "application"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3"
surrealdb = { version = "1.0.0-beta.9" }
workflow_visualizer = { path = "../workflow_visualizer" }
[target.'cfg(target_os = "android")'.dependencies]
log = "0.4.17"
android_logger = "0.13.1"
[lib]
name = "application"
crate-type = ["cdylib"]
path = "src/main.rs"
