[package]
name = "application"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3"
surrealdb = { version = "1.0.0-beta.9" }
workflow_visualizer = { path = "../workflow_visualizer" }

[lib]
name = "main"
crate-type = ["cdylib"]
path = "src/main.rs"
