[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true

[serve]
address = "127.0.0.1"
port = 8080
open = true
no_autoreload = true

[clean]
dist = "dist"
cargo = false

[tools]
wasm_bindgen = "0.2.86"
wasm_opt = "version_110"