[workspace]
members = ["workflow_visualizer", "application", "website", "icon_editor", "application_logic"]
resolver = "2"
[profile.release]
debug = 1
#lto = true
#opt-level = "s"
[profile.dev]
#opt-level = 1