[workspace]
members = ["workflow_visualizer", "application", "website", "application_logic", "placement_tool", "placement_tool_logic"]
resolver = "2"
[profile.release]
debug = 1
#lto = true
#opt-level = "s"
[profile.dev]
#opt-level = 1