[package]
name = "desktop_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
app = {path = "../app"}
futures = "0.3.24"
winit = "0.27.2"
