[package]
name = "workflow_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.10.0"
winit = "0.28.2"
wgpu = { version = "0.15.1", features = ["webgl"] }
bytemuck = { version = "1.13.1", features = ["derive"] }
web-sys = { version = "0.3.59", features = [
    "Window",
    "Performance",
    "Screen",
    "ScreenOrientation",
] }
js-sys = "0.3.61"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.33"
nalgebra = "0.32.1"
wasm-bindgen-cli-support = "0.2.83"
serde = { version = "1.0.154", features = ["derive"] }
rmp-serde = "1.1.1"
fontdue = "0.7.2"
bitflags = "1.3.2"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.24.2", features = ["full"] }
env_logger = "0.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["fs", "compression-gzip", "cors", "set-header", "trace"] }
axum = { version = "0.6.7", features = ["http2", "macros", "headers"] }
axum-server = { version = "0.4.6", features = ["tls-rustls"] }
futures = "0.3.26"
[[example]]
name = "app"
path = "examples/app.rs"