[alias]
desktop_build = "build --package workflow_visualizer --example app"
desktop_run = "run --package workflow_visualizer --example app"
web = "run --package workflow_visualizer --release --example app --"
[build]
rustflags = [
    "--cfg=web_sys_unstable_apis"
]