[alias]
desktop_build = "build --package mise_en_place_app --bin mise_en_place_app"
desktop_run = "run --package mise_en_place_app --bin mise_en_place_app"
web = "run --package mise_en_place_app --bin mise_en_place_app --"
[build]
rustflags = [
    "--cfg=web_sys_unstable_apis"
]