[alias]
desktop_build = "build --package app"
desktop_run = "run --package app --bin app"
android_build = "apk build --target-dir android_rebuild_avoidance_target --package app --lib"
android_run = "apk run --release --target-dir android_rebuild_avoidance_target --package app --lib"
web_build = "run --release --package web_builder --"
[build]
rustflags = [
    "--cfg=web_sys_unstable_apis"
]