mod attributes;
mod font;
mod glyph;
mod layout;
mod rasterization;
mod render;
mod scale;
mod vertex;
pub use crate::text_step_out::attributes::add::{add_instances, growth, add_attributes, setup_added_instances};
pub use crate::text_step_out::attributes::remove::remove_instances;
pub use crate::text_step_out::attributes::{setup_attribute_buffers, setup_attributes};
pub use crate::text_step_out::attributes::write::write_attribute;
pub use crate::text_step_out::rasterization::placement::RasterizationPlacement;
pub use crate::text_step_out::render::TextRenderer;
pub use crate::text_step_out::rasterization::{rasterize_adds, rasterize_writes};
