pub use crate::text::plugin::TextPlugin;
pub use crate::text::render_group::TextBoundGuide;
pub use crate::text::scale::TextScaleAlignment;
pub use crate::text::text::{PartitionMetadata, Text, TextBundle, TextPartition};

mod atlas;
mod backend_system;
mod cache;
mod coords;
mod difference;
mod extraction;
mod font;
mod frontend_system;
mod glyph;
mod null_bit;
mod place;
mod plugin;
mod render_group;
mod renderer;
mod scale;
mod text;
mod vertex;
